"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./icomoon.css";
import "aos/dist/aos.css";
import "mapbox-gl/dist/mapbox-gl.css";
import AppProvider from "@/providers/AppProvider";
import { Header } from "@/components/ui";
import { usePathname } from "next/navigation";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AuthContext from "@/context/AuthContext";
import AuthProvider from "@/context/AuthContext";
import { ReactQueryProvider } from "@/providers/reactQueryProvider";
import { Inter } from "next/font/google";
import Footer from "@/components/ui/Footer";

const Slussen = localFont({
  src: [
    {
      path: "../../public/assets/fonts/slussen-mono/Slussen-Mono-Thin.woff",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/slussen-mono/Slussen-Mono-Extralight.woff",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/slussen-mono/Slussen-Mono-Light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/slussen-mono/Slussen-Mono-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/slussen-mono/Slussen-Mono-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/slussen-mono/Slussen-Mono-Semibold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/slussen-mono/Slussen-Mono-Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/slussen-mono/Slussen-Mono-Black.woff",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-slussen-mono",
});

const Futura = localFont({
  src: [
    {
      path: "../../public/assets/fonts/FuturaPT-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/FuturaPT-semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/FuturaPT-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/FuturaNormal.woff2",
      weight: "400",
      style: "normal",
    } /* ,
    {
      path: "../../public/assets/fonts/Segoe UI Symbol.ttf",
      weight: "500",
      style: "normal",
    }, */,
  ],
  variable: "--font-futura",
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});

// export const metadata: Metadata = {
//   title: "Sequel",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body
        className={`${Futura.variable} ${inter.variable} ${Slussen.variable}`}
      >
        <AppProvider>
          <ReactQueryProvider>
            <Header />
            <main id="main-inn" style={{ height: "calc(100vh - 138px)" }}>
              {children}

              {pathname === "/" ? null : <Footer />}
            </main>

            <ToastContainer position="top-center" autoClose={2000} />
          </ReactQueryProvider>
        </AppProvider>
      </body>
    </html>
  );
}
