"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./icomoon.css";
import "aos/dist/aos.css";
import "mapbox-gl/dist/mapbox-gl.css";
import AppProvider from "@/providers/AppProvider";
import { Footer, Header } from "@/components/ui";
import { usePathname } from "next/navigation";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AuthContext from "@/context/AuthContext";
import AuthProvider from "@/context/AuthContext";
import { ReactQueryProvider } from "@/providers/reactQueryProvider";

const Futura = localFont({
  src: [
    {
      path: "../../public/assets/fonts/FuturaPT-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/FuturaPT-semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/FuturaPT-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/FuturaNormal.woff2",
      weight: "400",
      style: "normal",
    } /* ,
    {
      path: "../../public/assets/fonts/Segoe UI Symbol.ttf",
      weight: "500",
      style: "normal",
    }, */,
  ],
  variable: "--font-futura",
});

// export const metadata: Metadata = {
//   title: "Sequel",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={`${Futura.variable} `}>
        <AppProvider>
          <ReactQueryProvider>
            {/* {pathname.includes("app") || pathname.includes("auth") ? (
              ""
            ) : (
              <Header />
            )} */}
            <Header />
            <main id="main-inn" style={{height: 'calc(100vh - 138px)'}}>{children}</main>
            <Footer />
            {/* {pathname.includes("app") || pathname.includes("auth") ? (
              ""
            ) : (
              <Footer />
            )} */}
            <ToastContainer position="top-center" autoClose={2000} />
          </ReactQueryProvider>
        </AppProvider>
      </body>
    </html>
  );
}
