const GalleryData = [
  {
    img: "/assets/images/gellaryview/citybox.png",
    heading: "Citybox Tallinn City Center",
    num: "5.0",
    subheading: "   Tallinn City Center, Tallinn",
    price: "$89.33",
  },
  {
    img: "/assets/images/gellaryview/tallinn.png",
    heading: "Tallinn Oasis Studios",
    num: "5.0",
    subheading: "   Lasnamae, Tallinn",
    price: "$72.95",
  },
  {
    img: "/assets/images/gellaryview/center.png",
    heading: "Center Hotel",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$40.41",
  },
  {
    img: "/assets/images/gellaryview/city.png",
    heading: "City Yard Inn Hotel",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$51.05",
  },
  {
    img: "/assets/images/gellaryview/hestila.png",
    heading: "Hestia Hotel Seaport",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$100.05",
  },
  {
    img: "/assets/images/gellaryview/hoteldez.png",
    heading: "Hotel Dzingel",
    num: "5.0",
    subheading: "Nomme, Tallinn",
    price: "$48.92",
  },
  {
    img: "/assets/images/gellaryview/tallincity.png",
    heading: "Tallinn City Apartments",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$66.68",
  },
  {
    img: "/assets/images/gellaryview/hestilahotel.png",
    heading: "Hestia Hotel Susi",
    num: "5.0",
    subheading: "Lasnamae, Tallinn",
    price: "$84.01",
  },
  {
    img: "/assets/images/gellaryview/dorzell.png",
    heading: "Dorell",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$48.27",
  },
  {
    img: "/assets/images/gellaryview/ibless.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/citybox2.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/park.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/viliahotel.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/hotelstar.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/hotelroom.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/citybox2.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/park.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/viliahotel.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/hotelstar.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/hotelroom.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/citybox2.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/park.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/viliahotel.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/hotelstar.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/hotelroom.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/citybox2.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/park.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/viliahotel.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/hotelstar.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
  {
    img: "/assets/images/gellaryview/hotelroom.png",
    heading: "Ibis Tallinn Center",
    num: "5.0",
    subheading: "Tallinn City Center, Tallinn",
    price: "$93.11",
  },
];
export { GalleryData };
